api_platform:
    title: 'gcl'
    description: 'Symfony API pour la gestion des etablissement (colleges, lycees).'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
