#index:
#    path: /
#    controller: App\Controller\DefaultController::index
login_check:
    path:     /login_check
    methods:  [POST]

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
apport_get_entrant:
    path: /apports/apportEntrant
    methods: ['GET']
    defaults:
        _controller: App\Controllerr::ApportEntrant
        _api_resource_class: App\Entity\Apport
        _api_collection_operation_name: apport_get_entrant